export const genreOptions = [
        "--Genre--",
        "Racing",
        "Shooter",
        "Adventure",
        "Action",
        "RPG",
        "Fighting",
        "Puzzle",
        "Strategy",
        "Arcade",
        "Simulation",
        "Sports",
        "Card",
        "Family",
        "Board Games",
        "Educational",
        "Casual",
        "Indie",
        "Massively Multiplayer",
        "Platformer"
];
export const genresObject = {
        "Racing": 1,
        "Shooter": 2,
        "Adventure": 3,
        "Action": 4,
        "RPG": 5,
        "Fighting": 6,
        "Puzzle": 7,
        "Strategy": 10,
        "Arcade": 11,
        "Simulation": 14,
        "Sports": 15,
        "Card": 17,
        "Family": 19,
        "Board Games": 28,
        "Educational": 34,
        "Casual": 40,
        "Indie": 51,
        "Massively Multiplayer": 59,
        "Platformer": 83
};

export const platformOptions = ['--Platform--',
        'Xbox One',
        'iOS',
        'PC',
        'macOS',
        'Linux',
        'Nintendo Switch',
        'Nintendo 3DS',
        'Nintendo DS',
        'Wii U',
        'Wii',
        'Neo Geo',
        'Nintendo DSi',
        'Xbox 360',
        'PlayStation 2',
        'PlayStation 3',
        'PSP',
        'PlayStation 4',
        'PS Vita',
        'Android',
        'Atari Flashback',
        'Atari 2600',
        'Game Boy Advance',
        'Atari 8-bit',
        'Game Boy',
        'PlayStation',
        'Atari 7800',
        'Atari 5200',
        'Atari ST',
        'Apple II',
        'Game Boy Color',
        'Atari Lynx',
        'NES',
        'Atari XEGS',
        'Classic Macintosh',
        'SEGA Master System',
        'Game Gear',
        'SNES',
        'Xbox',
        'Nintendo 64',
        'GameCube']

export const platformsObject = {

        "Xbox One": 1,
        "iOS": 3,
        "PC": 4,
        "macOS": 5,
        "Linux": 6,
        "Nintendo Switch": 7,
        "Nintendo 3DS": 8,
        "Nintendo DS": 9,
        "Wii U": 10,
        "Wii": 11,
        "Neo Geo": 12,
        "Nintendo DSi": 13,
        "Xbox 360": 14,
        "PlayStation 2": 15,
        "PlayStation 3": 16,
        "PSP": 17,
        "PlayStation 4": 18,
        "PS Vita": 19,
        "Android": 21,
        "Atari Flashback": 22,
        "Atari 2600": 23,
        "Game Boy Advance": 24,
        "Atari 8-bit": 25,
        "Game Boy": 26,
        "PlayStation": 27,
        "Atari 7800": 28,
        "Atari ST": 31,
        "Apple II": 41,
        "Game Boy Color": 43,
        "Atari Lynx": 46,
        "NES": 49,
        "Atari XEGS": 50,
        "Classic Macintosh": 55,
        "SEGA Master System": 74,
        "Game Gear": 77,
        "SNES": 79,
        "Xbox": 80,
        "Nintendo 64": 83,
        "GameCube": 105
}